version: "3.1"

services:
  mysql_db:
    image: mysql
    ports:
      - "3307-3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=techamorsaude
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: always

  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
